all:
  hosts:
    postgres-servers:
      hosts:
        server1:
          ansible_host: 192.168.1.1
        server2:
          ansible_host: 192.168.1.2
      vars:
        scope: db
    patroniname:
      hosts:
        server1:
          db_name: db01
        server2:
          db_name: db02
    pg-replicas:
      hosts:
        192.168.1.2: {}
    pg-main:
      hosts:
        192.168.1.1: {}
    servers:
      hosts:
        192.168.1.1: {}
        192.168.1.2: {}
    etcd_cluster:
      hosts:
        etcd1:
          ansible_host: 192.168.1.3:2379
        etcd2:
          ansible_host: 192.168.1.4:2379
    etcd_clusters:
      hosts:
        etcd1:
          ansible_host: 192.168.1.3
        etcd2:
          ansible_host: 192.168.1.4
    etcd_clusters_name:
      hosts:
        etcd1:
          name: etcd1
        etcd2:
          name: etcd2
    pg-pmm-cluster:
      hosts:
        pg-db: {}
    pgbadger:
      hosts:
        if_using_pgbader: {}
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: yzd123
    PGPASSWORD: abc
    appuser: xyz12nza
